************* Module dhsc_data_tools
dhsc_data_tools\__init__.py:3:0: C0304: Final newline missing (missing-final-newline)
dhsc_data_tools\__init__.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module dhsc_data_tools.dac_odbc
dhsc_data_tools\dac_odbc.py:11:0: C0301: Line too long (110/100) (line-too-long)
dhsc_data_tools\dac_odbc.py:15:0: C0301: Line too long (110/100) (line-too-long)
dhsc_data_tools\dac_odbc.py:20:0: C0301: Line too long (150/100) (line-too-long)
dhsc_data_tools\dac_odbc.py:21:0: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\dac_odbc.py:27:0: C0301: Line too long (129/100) (line-too-long)
dhsc_data_tools\dac_odbc.py:67:0: C0304: Final newline missing (missing-final-newline)
dhsc_data_tools\dac_odbc.py:1:0: C0114: Missing module docstring (missing-module-docstring)
dhsc_data_tools\dac_odbc.py:2:0: E0401: Unable to import 'msal' (import-error)
dhsc_data_tools\dac_odbc.py:3:0: E0401: Unable to import 'pyodbc' (import-error)
dhsc_data_tools\dac_odbc.py:4:0: E0401: Unable to import 'pypac' (import-error)
dhsc_data_tools\dac_odbc.py:27:8: W0707: Consider explicitly re-raising using 'except KeyError as exc' and 'raise KeyError('TENANT_NAME environment variable not found. \nPlease load this as it is required to connect to the DAC.') from exc' (raise-missing-from)
dhsc_data_tools\dac_odbc.py:46:4: C0103: Variable name "KVC" doesn't conform to snake_case naming style (invalid-name)
************* Module dhsc_data_tools.keyvault
dhsc_data_tools\keyvault.py:20:0: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\keyvault.py:30:0: C0301: Line too long (107/100) (line-too-long)
dhsc_data_tools\keyvault.py:32:0: C0301: Line too long (101/100) (line-too-long)
dhsc_data_tools\keyvault.py:34:0: C0301: Line too long (104/100) (line-too-long)
dhsc_data_tools\keyvault.py:37:0: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\keyvault.py:50:0: C0304: Final newline missing (missing-final-newline)
dhsc_data_tools\keyvault.py:1:0: C0114: Missing module docstring (missing-module-docstring)
dhsc_data_tools\keyvault.py:2:0: E0401: Unable to import 'azure.keyvault.secrets' (import-error)
dhsc_data_tools\keyvault.py:3:0: E0401: Unable to import 'azure.identity' (import-error)
dhsc_data_tools\keyvault.py:5:0: C0103: Class name "kvConnection" doesn't conform to PascalCase naming style (invalid-name)
dhsc_data_tools\keyvault.py:28:16: C0103: Attribute name "KVUri" doesn't conform to snake_case naming style (invalid-name)
dhsc_data_tools\keyvault.py:26:16: W0707: Consider explicitly re-raising using 'except AttributeError as exc' and 'raise AttributeError('KEY_VAULT_NAME environment variable not found.') from exc' (raise-missing-from)
dhsc_data_tools\keyvault.py:5:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module dhsc_data_tools.remote_compute
dhsc_data_tools\remote_compute.py:15:0: C0301: Line too long (101/100) (line-too-long)
dhsc_data_tools\remote_compute.py:27:0: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\remote_compute.py:28:51: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\remote_compute.py:31:0: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\remote_compute.py:36:38: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\remote_compute.py:37:35: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\remote_compute.py:38:39: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\remote_compute.py:42:38: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\remote_compute.py:43:35: C0303: Trailing whitespace (trailing-whitespace)
dhsc_data_tools\remote_compute.py:48:0: C0304: Final newline missing (missing-final-newline)
dhsc_data_tools\remote_compute.py:1:0: C0114: Missing module docstring (missing-module-docstring)
dhsc_data_tools\remote_compute.py:3:0: E0401: Unable to import 'databricks.connect' (import-error)
dhsc_data_tools\remote_compute.py:26:21: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
dhsc_data_tools\remote_compute.py:26:21: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dhsc_data_tools\remote_compute.py:1:0: W0611: Unused import os (unused-import)

-----------------------------------
Your code has been rated at 0.00/10

